/*!
 * error.h - errors for mako
 * Copyright (c) 2020, Christopher Jeffrey (MIT License).
 * https://github.com/chjj/mako
 */

#ifndef BTC_ERROR_H
#define BTC_ERROR_H

#ifdef __cplusplus
extern "C" {
#endif

#include "common.h"
#include "types.h"

/*
 * Constants
 */

enum btc_errno {
  BTC_OK = 0,
  BTC_ERR_BIP30,
  BTC_ERR_BLOCK_SIGOPS,
  BTC_ERR_BLOCK_SIZE,
  BTC_ERR_BLOCK_VERSION,
  BTC_ERR_BLOCK_WEIGHT,
  BTC_ERR_CB_AMOUNT,
  BTC_ERR_CB_HEIGHT,
  BTC_ERR_CB_MISSING,
  BTC_ERR_CB_MULTIPLE,
  BTC_ERR_CB_SIZE,
  BTC_ERR_CHECKPOINT_DELTA,
  BTC_ERR_CHECKPOINT_FORK,
  BTC_ERR_CHECKPOINT_MISMATCH,
  BTC_ERR_COINBASE,
  BTC_ERR_DIFFBITS,
  BTC_ERR_DUPLICATE,
  BTC_ERR_DUST,
  BTC_ERR_FEE_HIGH,
  BTC_ERR_FEE_LOW,
  BTC_ERR_FEE_RANGE,
  BTC_ERR_FINALITY,
  BTC_ERR_HIGH_HASH,
  BTC_ERR_INPUT_RANGE,
  BTC_ERR_INPUTS_DUPLICATE,
  BTC_ERR_INPUTS_EMPTY,
  BTC_ERR_INPUTS_MISSING,
  BTC_ERR_INPUTS_NONSTANDARD,
  BTC_ERR_INPUTS_SPENT,
  BTC_ERR_KNOWN_INVALID,
  BTC_ERR_LOCKS,
  BTC_ERR_MEMPOOL_CHAIN,
  BTC_ERR_MEMPOOL_FULL,
  BTC_ERR_MERKLE_ROOT,
  BTC_ERR_MULTISIG,
  BTC_ERR_NONFINAL,
  BTC_ERR_NOTFOUND,
  BTC_ERR_NULLDATA,
  BTC_ERR_OUTPUT_RANGE,
  BTC_ERR_OUTPUTS_EMPTY,
  BTC_ERR_PREMATURE_CSV,
  BTC_ERR_PREMATURE_SPEND,
  BTC_ERR_PREMATURE_WITNESS,
  BTC_ERR_PREVBLK,
  BTC_ERR_PREVOUT_NULL,
  BTC_ERR_REPLACEMENT,
  BTC_ERR_SCRIPT_CONSENSUS,
  BTC_ERR_SCRIPT_POLICY,
  BTC_ERR_SCRIPTPUBKEY,
  BTC_ERR_SCRIPTSIG_PUSH,
  BTC_ERR_SCRIPTSIG_SIZE,
  BTC_ERR_TOO_NEW,
  BTC_ERR_TOO_OLD,
  BTC_ERR_TX_BASE,
  BTC_ERR_TX_DUPLICATE,
  BTC_ERR_TX_IN_MEMPOOL,
  BTC_ERR_TX_KNOWN,
  BTC_ERR_TX_SIGOPS,
  BTC_ERR_TX_SIZE,
  BTC_ERR_TX_VERSION,
  BTC_ERR_TX_WEIGHT,
  BTC_ERR_WITNESS_MERKLE,
  BTC_ERR_WITNESS_NONCE,
  BTC_ERR_WITNESS_NONSTANDARD,
  BTC_ERR_WITNESS_UNEXPECTED
};

/*
 * Helpers
 */

BTC_EXTERN const char *
btc_error_name(btc_errno_t code);

BTC_EXTERN const char *
btc_error_reason(btc_errno_t code);

BTC_EXTERN int
btc_error_score(btc_errno_t code);

BTC_EXTERN int
btc_error_malleable(btc_errno_t code);

#ifdef __cplusplus
}
#endif

#endif /* BTC_ERROR_H */
