#!/bin/sh

# watcom-env - watcom env for libtorsion
# Copyright (c) 2020, Christopher Jeffrey (MIT License).
# https://github.com/bcoin-org/libtorsion

export WATCOM=${WATCOM:-/opt/watcom}
export PATH="$WATCOM/binl64:$WATCOM/binl:$PATH"
export INCLUDE="$WATCOM/lh"

exec "$@"
